// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiDfjtsX_XJA3L3uSk02TxVYqR1dxSEEE',
    appId: '1:1046574417828:web:a77cc29dbe79876e9ce331',
    messagingSenderId: '1046574417828',
    projectId: 'accenture-29766',
    authDomain: 'accenture-29766.firebaseapp.com',
    storageBucket: 'accenture-29766.appspot.com',
    measurementId: 'G-W89VTPWNEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDyPoVRq9ym6W_YDuFBR1MTBbjTl6eJvE',
    appId: '1:1046574417828:android:6c115b81e753c1c49ce331',
    messagingSenderId: '1046574417828',
    projectId: 'accenture-29766',
    storageBucket: 'accenture-29766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgywA8y3B1uRWdiJSwyU5pHblgwJz0tnA',
    appId: '1:1046574417828:ios:5c74f36cf43baafe9ce331',
    messagingSenderId: '1046574417828',
    projectId: 'accenture-29766',
    storageBucket: 'accenture-29766.appspot.com',
    iosClientId: '1046574417828-h3p5p05816neuoh01kq0tnscmjj7vfgi.apps.googleusercontent.com',
    iosBundleId: 'com.skytechnohub.chat',
  );
}
